### Login as admin
# @name loginAdmin
GET https://localhost/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdmin.response.headers.Authorization}}

### Login as manfred
# @name loginManfred
GET https://localhost/authenticate
Authorization: Basic manfred:asdf

@manfredToken = {{loginManfred.response.headers.Authorization}}

### create first thread as admin
# @name firstThread
POST https://localhost/forumThreads
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Mein erstes Forum",
    "description": "Das ist ein erstes Forum, das ich im Rahmen der Tests angelegt habe"
}
###
@firstThreadID = {{firstThread.response.body._id}}

### create second thread as manfred
# @name secondThread
POST https://localhost/forumThreads
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "name": "Mein zweites Forum",
    "description": "Das ist ein zweites Forum, das ich im Rahmen der Tests angelegt habe"
}
###
@secondThreadID = {{secondThread.response.body._id}}

## create three messages for first thread
# @name firstThreadFirstMessage
POST https://localhost/forumMessages
Authorization: {{adminToken}}
Content-Type: application/json

{
    "forumThreadID": "{{firstThreadID}}",
    "title": "Thread 1 Msg 1",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}
###
@firstThreadFirstMessageID = {{firstThreadFirstMessage.response.body._id}}

# @name firstThreadSecondMessage
POST https://localhost/forumMessages
Authorization: {{adminToken}}
Content-Type: application/json

{
    "forumThreadID": "{{firstThreadID}}",
    "title": "Thread 1 Msg 2",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}
###
@firstThreadSecondMessageID = {{firstThreadSecondMessage.response.body._id}}

# @name firstThreadThirdMessage
POST https://localhost/forumMessages
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "forumThreadID": "{{firstThreadID}}",
    "title": "Thread 1 Msg 3",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}
###
@firstThreadThirdMessageID = {{firstThreadThirdMessage.response.body._id}}

## create three messages for second forum
# @name secondThreadFirstMessage
POST https://localhost/forumMessages
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "forumThreadID": "{{secondThreadID}}",
    "title": "Thread 2 Msg 1",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}
###
@secondThreadFirstMessageID = {{secondThreadFirstMessage.response.body._id}}

# @name secondThreadSecondMessage
POST https://localhost/forumMessages
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "forumThreadID": "{{secondThreadID}}",
    "title": "Thread 2 Msg 2",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}
###
@secondThreadSecondMessageID = {{secondThreadSecondMessage.response.body._id}}

# @name secondThreadThirdMessage
POST https://localhost/forumMessages
Authorization: {{adminToken}}
Content-Type: application/json

{
    "forumThreadID": "{{secondThreadID}}",
    "title": "Thread 2 Msg 3",
    "text": "Das wollte ich nur kurz in das Forum schreiben."
}
###
@secondThreadThirdMessageID = {{secondThreadThirdMessage.response.body._id}}

### get all messages from all threads (6 expected)
GET https://localhost/forumMessages

### get all messages from first thread (3 expected)
GET https://localhost/forumMessages?forumThreadID={{firstThreadID}}

### get all messages from second thread via downstream route
GET https://localhost/forumThreads/{{secondThreadID}}/forumMessages

### update second message of second thread as admin (should work)
PUT https://localhost/forumMessages/{{secondThreadSecondMessageID}}
Authorization: {{adminToken}}
Content-Type: application/json

{
    "text": "Hab mir den Text doch anders überlegt"
}

### update first message of first thread as manfred (should not work)
PUT https://localhost/forumMessages/{{firstThreadFirstMessageID}}
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "text": "Haha es geht doch! Sollte es aber nicht"
}

### delete third message of second thread as manfred (should not work)
DELETE https://localhost/forumMessages/{{secondThreadThirdMessageID}}
Authorization: {{manfredToken}}

### delete third message of second thread as admin (should work)
DELETE https://localhost/forumMessages/{{secondThreadThirdMessageID}}
Authorization: {{adminToken}}

### delete first thread (and every message with it)
DELETE https://localhost/forumThreads/{{firstThreadID}}
Authorization: {{adminToken}}

### show every message of first thread (thread should not be found)
GET https://localhost/forumMessages?forumThreadID={{firstThreadID}}