### Re-test Meilenstein 1, es sollte der Standard-Admin in der Datenbank sein
https://localhost/publicUsers

### Login mit Basic Authentication als admin mit korrekten Credentials admin:123
# @name loginAdminCorrect
GET https://localhost/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

### Login mit Basic Authentication als admin mit falschen Credentials
GET https://localhost/authenticate
Authorization: Basic admin:1234

### Lege neuen user manfred an
POST https://localhost/users
Authorization: {{adminToken}}
Content-Type: application/json

{
    "userID": "manfred",
    "userName": "Manfred Mustermann",
    "password": "asdf"
}

### Abrufen des angelegten Users ohne Token
GET https://localhost/users/manfred

### Abrufen des angelegten Users mit dem Admin-Token
GET https://localhost/users/manfred
Authorization: {{adminToken}}

### Login mit Basic Authentication als manfred mit korrekten Credentials manfred:asdf
# @name loginManfredCorrect
GET https://localhost/authenticate
Authorization: Basic bWFuZnJlZDphc2Rm

@manfredToken = {{loginManfredCorrect.response.headers.Authorization}}

### Auflisten aller Nutzer ohne Token
https://localhost/users

### Auflisten aller Nutzer mit Token von admin
https://localhost/users
Authorization: {{adminToken}}

### Auflisten aller Nutzer mit Token von manfred
https://localhost/users
Authorization: {{manfredToken}}





////////////////////////// ForumThreads





### Auflisten aller Foren ohne Token
GET https://localhost/forumThreads

### Lege ein erstes Forum an, der Administrator ist owner
# @name createFirstForumRequest
POST https://localhost/forumThreads
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Mein erstes Forum",
    "description": "Das ist ein erstes Forum, das ich im Rahmen der Tests angelegt habe"
}

###
@firstForumThreadID = {{createFirstForumRequest.response.body._id}}

### Lege ein zweites Forum an, der Administrator ist owner
# @name createSecondForumRequest
POST https://localhost/forumThreads
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Mein zweites Forum",
    "description": "Das ist ein zweites Forum, das ich im Rahmen der Tests angelegt habe"
}

###
@secondForumThreadID = {{createSecondForumRequest.response.body._id}}

### Lege ein drittes Forum an, Manfred ist owner
# @name createThirdForumRequest
POST https://localhost/forumThreads
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "name": "Mein drittes Forum",
    "description": "Das ist ein drittes Forum, welches Manfred gehoert."
}

###
@thirdForumThreadID = {{createThirdForumRequest.response.body._id}}

### Auflisten aller Foren ohne Token, nun sollte es drei Foren geben
https://localhost/forumThreads

### Abrufen von dem ersten angelegten Forum-Thread
https://localhost/forumThreads/{{firstForumThreadID}}

### Abrufen von dem zweiten angelegten Forum-Thread
https://localhost/forumThreads/{{secondForumThreadID}}

### Ändere die forumDescription in dem ersten Forum als admin
PUT https://localhost/forumThreads/{{firstForumThreadID}}
Authorization: {{adminToken}}
Content-Type: application/json

{
    "description": "Das ist der neue Text, warum auch nicht."
}

### Ändere die forumDescription in dem zweiten Forum als manfred
PUT https://localhost/forumThreads/{{secondForumThreadID}}
Authorization: {{manfredToken}}
Content-Type: application/json

{
    "description": "Das sollte nicht funktionieren."
}

### Ändere die forumDescription in dem dritten Forum als admin (manfred ist owner)
PUT https://localhost/forumThreads/{{thirdForumThreadID}}
Authorization: {{adminToken}}
Content-Type: application/json

{
    "description": "Der Admin hat das hier geändert"
}

### Auflisten der Foren des aktuellen users
GET https://localhost/forumThreads/myForumThreads
Authorization: {{adminToken}}

### Auflisten der Foren eines bestimmten user
GET https://localhost/forumThreads?ownerID=manfred

### Lösche den ersten angelegten Forum-Thread mit richtigem Token
DELETE https://localhost/forumThreads/{{firstForumThreadID}}
Authorization: {{adminToken}}

### Lösche den zweiten angelegten Forum-Thread mit falschem Token
DELETE https://localhost/forumThreads/{{secondForumThreadID}}
Authorization: {{manfredToken}}

### Lösche den dritten angelegten Forum-Thread mit admin Token (manfred ist owner)
DELETE https://localhost/forumThreads/{{thirdForumThreadID}}
Authorization: {{adminToken}}

### Lösche den User manfred
DELETE https://localhost/users/manfred
Authorization: {{adminToken}}